# Generated by Django 2.1 on 2018-08-19 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing',
            old_name='amount',
            new_name='price',
        ),
    ]
