# Generated by Django 3.1.4 on 2020-12-21 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180819_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='pricing_items',
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.cart')),
                ('pricing_item', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.pricing')),
            ],
        ),
    ]
