# Generated by Django 3.1.4 on 2020-12-21 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20201221_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='pricing_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.pricing'),
        ),
    ]
